### ISSUE TITLE
Re-implement docker installation

### ISSUE THREAD

**Issue by SirHazza** [VerifiedJoseph/vigilant#151]
Currently Vigilant can only be installed manually, installation with a docker container would be greatly appreciated.

I can see this [was originally an option](https://github.com/VerifiedJoseph/vigilant/commit/fdeb2137003726ac5cdfe48cc460cd348be9756e). But I couldn't find any information on why it was removed, other than the docker image it's self was taken down. Alternatively, guidance on how to build the docker image (as you do currently for your dev workspace) and the appropriate docker compose configuration would also be useful. Thank you!

**Comment by VerifiedJoseph** [comment]
Hello, SirHazza.

Thank you for your request. I've released version 1.1.0 which re-implements docker. 

Installation docs:
https://github.com/VerifiedJoseph/vigilant/blob/main/docs/install.md#docker-compose
