### ISSUE TITLE
Can't start docker container "Feeds error: Indentation problem"

### ISSUE THREAD

**Issue by SirHazza** [VerifiedJoseph/vigilant#168]
Thank you for providing the docker installation option and it's documentation!

Following the docker compose and feeds setup provided, I'm unable to start the docker container. Getting the following error:

```
Starting Vigilant 1.1.0 daemon...
Loading feeds.yaml (feeds.yaml)
Feeds error: Indentation problem at line 3 (near "name: Met Office weather warnings").
```

I had originally tried to start the container with my own feeds.yaml file. But as you can see, even when creating a new feeds file and copy/pasting the provided example, the error still occurs.

**Comment by VerifiedJoseph** [comment]
My bad, sorry. YAML formatting of the example in [docs/feeds.md](https://github.com/VerifiedJoseph/vigilant/blob/main/docs/feeds.md) was incorrect. Fixed in #169
