### ISSUE TITLE
Any Plans to Support ntfy.sh Token Authentication?

### ISSUE THREAD

**Issue by timnolte** [VerifiedJoseph/vigilant#98]
I'd prefer to configure this to use a Token for sending to my ntfy.sh server rather than using Basic Auth username/password. Are there any plans to support this, like your PHP library?

**Comment by VerifiedJoseph** [comment]
I've been meaning to add support for this since last year but never got around to it. Anyway #102 addresses this.

**Comment by timnolte** [comment]
So I'm not sure if I have the token verification configured wrong but I'm noticing that I've received the following error in a recent run.

> [Notification error] [Ntfy] forbidden (code: 40301)

**Comment by timnolte** [comment]
Disregard, I just realized that the `NOTIFICATION_NTFY_AUTH` configuration was change from `true` to `password` or `token`.

**Comment by timnolte** [comment]
I also just tried changing it to username/password and I'm also receiving an authentication error. I was also trying with the URL using both a trailing slash and without.

**Comment by timnolte** [comment]
@VerifiedJoseph so, looking at your tests and your code and it appears your documentation is wrong and the ntfy configuration settings are all missing `VIGILANT_` as the leading name requirement.

https://github.com/VerifiedJoseph/vigilant/blob/main/docs/configuration.md

**Comment by timnolte** [comment]
I did confirm that by properly adding the missing leading `VIGILANT_` it is now working.

**Comment by VerifiedJoseph** [comment]
Oops, my bad, should've noticed that. I've merged #108
